# Generated by Django 5.1.3 on 2024-11-17 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseeker',
            name='cv_file',
            field=models.FileField(blank=True, null=True, upload_to='cv/'),
        ),
    ]
