# Generated by Django 5.1.3 on 2024-12-22 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0002_jobseeker_cv_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobseeker',
            name='cv',
        ),
        migrations.AlterField(
            model_name='employer',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logo/'),
        ),
    ]
