# Generated by Django 5.1.3 on 2024-12-22 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0003_remove_jobseeker_cv_alter_employer_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employer',
            name='logo',
        ),
        migrations.AddField(
            model_name='employer',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_image/'),
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='profile_image',
            field=models.FileField(blank=True, null=True, upload_to='profile_image/'),
        ),
    ]
